name: react deploy

concurrency:
    group: production
    cancel-in-progress: true

on:
    push:
        branches: [ "main" ]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        environment: production
        steps:
            -   name: Clone repository
                uses: actions/checkout@v3
            -   name: Use Node.js
                uses: actions/setup-node@v3
                with:
                    node-version: 16
            -   name: Install dependencies
                run: npm ci
            -   name: Test
                run: npm test
                env:
                    CI: true
            -   name: Generate build
                run: npm run build
                env:
                    DISABLE_ESLINT_PLUGIN: true
            -   name: Deploy
                run: ./.github/scripts/deploy.sh
                shell: bash
                env:
                    PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
